//! On-disk sample-corpus harness (NFR-TEST-2).
//!
//! All other round-trips in the suite are synthetic and in-memory. This harness instead
//! commits a small set of *real* `.fits` files under `test/corpus/` and asserts that the
//! public `Fits.openFile` API can re-open each from disk and recover both its header
//! structure and its data byte-for-byte.
//!
//! The set is representative of the FITS structural zoo:
//!   1. `primary_image.fits`      — a primary IMAGE HDU (BITPIX 16, 2-D).
//!   2. `image_extension.fits`    — empty primary + an IMAGE extension (BITPIX -32, 2-D).
//!   3. `ascii_table.fits`        — primary + an ASCII `TABLE` (I/F/E columns).
//!   4. `binary_table.fits`       — primary + a `BINTABLE` (I/J/E/A columns).
//!   5. `binary_table_vla.fits`   — primary + a `BINTABLE` with a `1PJ` variable-length column.
//!   6. `compressed_image.fits.gz`— a whole-file GZIP-compressed primary IMAGE.
//!
//! The files are generated by the library's own writers (pure-Zig satisfies the structural
//! intent of NFR-TEST-2; the externally-authored CFITSIO/Astropy golden subset is the
//! separate blocked item). Generation is deterministic, so the committed bytes are stable.
//!
//! Hermeticity: the harness reads from the committed `test/corpus/` path under the build
//! root (the cwd of `zig build test`). A member is (re)generated only when its file is
//! missing — on CI the committed files are read directly. No network or external tools are
//! used. The committed files were produced by running this very harness once with the
//! directory empty.
const std = @import("std");
const fits = @import("zigfitsio");

const Allocator = std.mem.Allocator;
const KeywordValue = fits.KeywordValue;

const corpus_dir = "test/corpus";

// ── Header builders (public-API mirrors of the per-module test helpers) ──────────────────

// Append the eight mandatory table-structure cards shared by ASCII and binary tables.
fn appendTableSpine(
    h: *fits.Header,
    alloc: Allocator,
    xtension: []const u8,
    naxis1: u64,
    nrows: u64,
    pcount: u64,
    tfields: u64,
) !void {
    try h.appendValue(alloc, "XTENSION", .{ .string = xtension }, null);
    try h.appendValue(alloc, "BITPIX", .{ .int = 8 }, null);
    try h.appendValue(alloc, "NAXIS", .{ .int = 2 }, null);
    try h.appendValue(alloc, "NAXIS1", .{ .int = @intCast(naxis1) }, null);
    try h.appendValue(alloc, "NAXIS2", .{ .int = @intCast(nrows) }, null);
    try h.appendValue(alloc, "PCOUNT", .{ .int = @intCast(pcount) }, null);
    try h.appendValue(alloc, "GCOUNT", .{ .int = 1 }, null);
    try h.appendValue(alloc, "TFIELDS", .{ .int = @intCast(tfields) }, null);
}

fn kw(buf: []u8, comptime prefix: []const u8, n: usize) []const u8 {
    return std.fmt.bufPrint(buf, prefix ++ "{d}", .{n}) catch unreachable;
}

// ── Member 1: a primary IMAGE HDU ────────────────────────────────────────────────────────

const img1_axes = [_]u64{ 4, 3 }; // 4 fast × 3 slow = 12 pixels
fn img1_pixel(i: usize) i16 {
    return @as(i16, @intCast(i)) * 7 - 11; // deterministic, signed, spans zero
}

fn genPrimaryImage(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.createFile(alloc, path, .{});
    defer f.deinit();
    const hdu = try f.appendImageHdu(.{ .bitpix = 16, .axes = &img1_axes });
    var view = try fits.ImageView.of(&f, hdu);
    var pix: [12]i16 = undefined;
    for (&pix, 0..) |*p, i| p.* = img1_pixel(i);
    try view.writeAll(i16, &pix, .{});
    try f.flush();
}

fn verifyPrimaryImage(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.openFile(alloc, path, .read_only, .{});
    defer f.deinit();
    try std.testing.expectEqual(@as(usize, 1), try f.hduCount());
    const hdu = try f.select(1);
    try std.testing.expectEqual(@as(i64, 16), try hdu.header.getValue(i64, "BITPIX"));
    try std.testing.expectEqual(@as(i64, 2), try hdu.header.getValue(i64, "NAXIS"));
    try std.testing.expectEqual(@as(i64, 4), try hdu.header.getValue(i64, "NAXIS1"));
    try std.testing.expectEqual(@as(i64, 3), try hdu.header.getValue(i64, "NAXIS2"));
    var view = try fits.ImageView.of(&f, hdu);
    var pix: [12]i16 = undefined;
    try view.readAll(i16, &pix, .{});
    for (pix, 0..) |got, i| try std.testing.expectEqual(img1_pixel(i), got);
}

// ── Member 2: empty primary + an IMAGE extension ─────────────────────────────────────────

const img2_axes = [_]u64{ 3, 2 }; // 6 pixels
fn img2_pixel(i: usize) f32 {
    return @as(f32, @floatFromInt(i)) * 0.5 - 1.0;
}

fn genImageExtension(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.createFile(alloc, path, .{});
    defer f.deinit();
    _ = try f.appendImageHdu(.{ .bitpix = 8, .axes = &.{} }); // empty primary
    const hdu = try f.appendImageHdu(.{ .bitpix = -32, .axes = &img2_axes }); // IMAGE ext
    var view = try fits.ImageView.of(&f, hdu);
    var pix: [6]f32 = undefined;
    for (&pix, 0..) |*p, i| p.* = img2_pixel(i);
    try view.writeAll(f32, &pix, .{});
    try f.flush();
}

fn verifyImageExtension(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.openFile(alloc, path, .read_only, .{});
    defer f.deinit();
    try std.testing.expectEqual(@as(usize, 2), try f.hduCount());
    const hdu = try f.select(2);
    try std.testing.expectEqual(fits.HduKind.image, hdu.kind);
    try std.testing.expectEqual(@as(i64, -32), try hdu.header.getValue(i64, "BITPIX"));
    try std.testing.expectEqual(@as(i64, 3), try hdu.header.getValue(i64, "NAXIS1"));
    try std.testing.expectEqual(@as(i64, 2), try hdu.header.getValue(i64, "NAXIS2"));
    var view = try fits.ImageView.of(&f, hdu);
    var pix: [6]f32 = undefined;
    try view.readAll(f32, &pix, .{});
    for (pix, 0..) |got, i| try std.testing.expectEqual(img2_pixel(i), got);
}

// ── Member 3: primary + an ASCII TABLE ───────────────────────────────────────────────────

const at_counts = [_]?i64{ 10, 20, 30 };
const at_flux = [_]?f64{ 1.25, 2.5, -3.75 };
const at_value = [_]?f64{ 0.5, -2.5, 100.0 };

fn genAsciiTable(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.createFile(alloc, path, .{});
    defer f.deinit();
    _ = try f.appendImageHdu(.{ .bitpix = 8, .axes = &.{} }); // primary

    // Layout: I6 [1,7) | F8.2 [7,15) | E15.7 [15,30). NAXIS1 = 29.
    var h = fits.Header.initEmpty();
    errdefer h.deinit(alloc);
    try appendTableSpine(&h, alloc, "TABLE", 29, 3, 0, 3);
    var b: [16]u8 = undefined;
    try h.appendValue(alloc, kw(&b, "TBCOL", 1), .{ .int = 1 }, null);
    try h.appendValue(alloc, kw(&b, "TFORM", 1), .{ .string = "I6" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 1), .{ .string = "COUNT" }, null);
    try h.appendValue(alloc, kw(&b, "TBCOL", 2), .{ .int = 7 }, null);
    try h.appendValue(alloc, kw(&b, "TFORM", 2), .{ .string = "F8.2" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 2), .{ .string = "FLUX" }, null);
    try h.appendValue(alloc, kw(&b, "TBCOL", 3), .{ .int = 15 }, null);
    try h.appendValue(alloc, kw(&b, "TFORM", 3), .{ .string = "E15.7" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 3), .{ .string = "VALUE" }, null);
    try h.ensureEnd(alloc);
    const hdu = try f.appendHdu(h);

    var t = try fits.AsciiTable.of(&f, hdu);
    defer t.deinit(alloc);
    try t.writeColumn(i64, .{ .index = 0 }, 0, &at_counts);
    try t.writeColumn(f64, .{ .index = 1 }, 0, &at_flux);
    try t.writeColumn(f64, .{ .index = 2 }, 0, &at_value);
    try f.flush();
}

fn verifyAsciiTable(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.openFile(alloc, path, .read_only, .{});
    defer f.deinit();
    try std.testing.expectEqual(@as(usize, 2), try f.hduCount());
    const hdu = try f.select(2);
    try std.testing.expectEqual(fits.HduKind.ascii_table, hdu.kind);
    try std.testing.expectEqual(@as(i64, 3), try hdu.header.getValue(i64, "TFIELDS"));

    var t = try fits.AsciiTable.of(&f, hdu);
    defer t.deinit(alloc);
    try std.testing.expectEqual(@as(u16, 3), t.columnCount());
    try std.testing.expectEqual(@as(u64, 3), t.rowCount());

    var oi: [3]?i64 = undefined;
    try t.readColumn(i64, .{ .name = "COUNT" }, 0, &oi);
    for (at_counts, oi) |want, got| try std.testing.expectEqual(want.?, got.?);
    var of_: [3]?f64 = undefined;
    try t.readColumn(f64, .{ .name = "FLUX" }, 0, &of_);
    for (at_flux, of_) |want, got| try std.testing.expectEqual(want.?, got.?);
    var oe: [3]?f64 = undefined;
    try t.readColumn(f64, .{ .name = "VALUE" }, 0, &oe);
    for (at_value, oe) |want, got| try std.testing.expectEqual(want.?, got.?);
}

// ── Member 4: primary + a BINARY TABLE ───────────────────────────────────────────────────

const bt_i16 = [_]i16{ 1, 2, 3 };
const bt_i32 = [_]i32{ 10, 20, 30 };
const bt_f32 = [_]f32{ 1.5, 2.5, 3.5 };

fn genBinaryTable(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.createFile(alloc, path, .{});
    defer f.deinit();
    _ = try f.appendImageHdu(.{ .bitpix = 8, .axes = &.{} }); // primary

    // 1I (2) + 1J (4) + 1E (4) + 8A (8) = 18 bytes/row.
    var h = fits.Header.initEmpty();
    errdefer h.deinit(alloc);
    try appendTableSpine(&h, alloc, "BINTABLE", 18, 3, 0, 4);
    var b: [16]u8 = undefined;
    try h.appendValue(alloc, kw(&b, "TFORM", 1), .{ .string = "1I" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 1), .{ .string = "I16" }, null);
    try h.appendValue(alloc, kw(&b, "TFORM", 2), .{ .string = "1J" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 2), .{ .string = "I32" }, null);
    try h.appendValue(alloc, kw(&b, "TFORM", 3), .{ .string = "1E" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 3), .{ .string = "F32" }, null);
    try h.appendValue(alloc, kw(&b, "TFORM", 4), .{ .string = "8A" }, null);
    try h.appendValue(alloc, kw(&b, "TTYPE", 4), .{ .string = "NAME" }, null);
    try h.ensureEnd(alloc);
    const hdu = try f.appendHdu(h);

    var t = try fits.BinTable.of(&f, hdu);
    defer t.deinit(alloc);
    try t.writeColumn(i16, .{ .index = 0 }, 0, &bt_i16, .{});
    try t.writeColumn(i32, .{ .index = 1 }, 0, &bt_i32, .{});
    try t.writeColumn(f32, .{ .index = 2 }, 0, &bt_f32, .{});

    var sbuf: [24]u8 = undefined; // 3 rows × 8A
    @memset(&sbuf, ' ');
    @memcpy(sbuf[0..5], "alpha");
    @memcpy(sbuf[8..12], "beta");
    @memcpy(sbuf[16..21], "gamma");
    try t.writeColumn(u8, .{ .name = "NAME" }, 0, &sbuf, .{});
    try f.flush();
}

fn verifyBinaryTable(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.openFile(alloc, path, .read_only, .{});
    defer f.deinit();
    try std.testing.expectEqual(@as(usize, 2), try f.hduCount());
    const hdu = try f.select(2);
    try std.testing.expectEqual(fits.HduKind.binary_table, hdu.kind);
    try std.testing.expectEqual(@as(i64, 4), try hdu.header.getValue(i64, "TFIELDS"));

    var t = try fits.BinTable.of(&f, hdu);
    defer t.deinit(alloc);
    try std.testing.expectEqual(@as(u16, 4), t.columnCount());
    try std.testing.expectEqual(@as(u64, 3), t.rowCount());

    var i16o: [3]i16 = undefined;
    var i32o: [3]i32 = undefined;
    var f32o: [3]f32 = undefined;
    try t.readColumn(i16, .{ .index = 0 }, 0, &i16o, .{});
    try t.readColumn(i32, .{ .name = "I32" }, 0, &i32o, .{});
    try t.readColumn(f32, .{ .index = 2 }, 0, &f32o, .{});
    try std.testing.expectEqualSlices(i16, &bt_i16, &i16o);
    try std.testing.expectEqualSlices(i32, &bt_i32, &i32o);
    try std.testing.expectEqualSlices(f32, &bt_f32, &f32o);

    var so: [24]u8 = undefined;
    try t.readColumn(u8, .{ .name = "NAME" }, 0, &so, .{});
    try std.testing.expectEqualStrings("alpha", std.mem.trimEnd(u8, so[0..8], " "));
    try std.testing.expectEqualStrings("beta", std.mem.trimEnd(u8, so[8..16], " "));
    try std.testing.expectEqualStrings("gamma", std.mem.trimEnd(u8, so[16..24], " "));
}

// ── Member 5: primary + a BINTABLE with a variable-length-array column (1PJ) ──────────────

const vla_row0 = [_]i32{ 10, 20, 30 };
const vla_row1 = [_]i32{ 7, 8 };
const vla_pcount: u64 = vla_row0.len * 4 + vla_row1.len * 4; // heap bytes (J = 4 bytes each)

fn genBinaryTableVla(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.createFile(alloc, path, .{});
    defer f.deinit();
    _ = try f.appendImageHdu(.{ .bitpix = 8, .axes = &.{} }); // primary

    // One 1PJ column: an 8-byte (2×i32) descriptor per row, PCOUNT heap bytes after the rows.
    var h = fits.Header.initEmpty();
    errdefer h.deinit(alloc);
    try appendTableSpine(&h, alloc, "BINTABLE", 8, 2, vla_pcount, 1);
    try h.appendValue(alloc, "TFORM1", .{ .string = "1PJ" }, null);
    try h.appendValue(alloc, "TTYPE1", .{ .string = "VLA" }, null);
    try h.ensureEnd(alloc);
    const hdu = try f.appendHdu(h);

    var t = try fits.BinTable.of(&f, hdu);
    defer t.deinit(alloc);
    var mgr = try fits.heap.HeapManager.initForTable(&t);
    defer mgr.deinit(alloc);
    try fits.heap.writeVlaCell(alloc, &t, &mgr, .{ .index = 0 }, 0, i32, &vla_row0);
    try fits.heap.writeVlaCell(alloc, &t, &mgr, .{ .index = 0 }, 1, i32, &vla_row1);
    try f.flush();
}

fn verifyBinaryTableVla(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.openFile(alloc, path, .read_only, .{});
    defer f.deinit();
    const hdu = try f.select(2);
    try std.testing.expectEqual(fits.HduKind.binary_table, hdu.kind);
    try std.testing.expectEqual(@as(i64, @intCast(vla_pcount)), try hdu.header.getValue(i64, "PCOUNT"));

    var t = try fits.BinTable.of(&f, hdu);
    defer t.deinit(alloc);
    const r0 = try fits.heap.readVlaCell(alloc, &t, .{ .index = 0 }, 0, i32);
    defer alloc.free(r0);
    const r1 = try fits.heap.readVlaCell(alloc, &t, .{ .name = "VLA" }, 1, i32);
    defer alloc.free(r1);
    try std.testing.expectEqualSlices(i32, &vla_row0, r0);
    try std.testing.expectEqualSlices(i32, &vla_row1, r1);
}

// ── Member 6: a whole-file GZIP-compressed primary IMAGE ─────────────────────────────────

const gz_axes = [_]u64{ 5, 4 }; // 20 pixels
fn gz_pixel(i: usize) i32 {
    return @as(i32, @intCast(i)) * 1000 - 5000;
}

fn genCompressedImage(alloc: Allocator, path: []const u8) !void {
    // Build the uncompressed image in memory, then export the whole file as a `*.fits.gz`
    // stream (`saveGzipFile`). `createFile` rejects a `.gz` path, so the gzip container is
    // produced from the in-memory handle.
    var mem = fits.MemoryDevice.init(alloc);
    defer mem.deinit();
    var f = try fits.Fits.create(alloc, mem.device(), .{});
    defer f.deinit();
    const hdu = try f.appendImageHdu(.{ .bitpix = 32, .axes = &gz_axes });
    var view = try fits.ImageView.of(&f, hdu);
    var pix: [20]i32 = undefined;
    for (&pix, 0..) |*p, i| p.* = gz_pixel(i);
    try view.writeAll(i32, &pix, .{});
    try f.flush();
    try f.saveGzipFile(path);
}

fn verifyCompressedImage(alloc: Allocator, path: []const u8) !void {
    var f = try fits.Fits.openFile(alloc, path, .read_only, .{}); // transparent inflate (.gz)
    defer f.deinit();
    const hdu = try f.select(1);
    try std.testing.expectEqual(@as(i64, 32), try hdu.header.getValue(i64, "BITPIX"));
    try std.testing.expectEqual(@as(i64, 5), try hdu.header.getValue(i64, "NAXIS1"));
    try std.testing.expectEqual(@as(i64, 4), try hdu.header.getValue(i64, "NAXIS2"));
    var view = try fits.ImageView.of(&f, hdu);
    var pix: [20]i32 = undefined;
    try view.readAll(i32, &pix, .{});
    for (pix, 0..) |got, i| try std.testing.expectEqual(gz_pixel(i), got);
}

// ── Driver ───────────────────────────────────────────────────────────────────────────────

const Member = struct {
    file: []const u8,
    gen: *const fn (Allocator, []const u8) anyerror!void,
    verify: *const fn (Allocator, []const u8) anyerror!void,
};

const members = [_]Member{
    .{ .file = corpus_dir ++ "/primary_image.fits", .gen = genPrimaryImage, .verify = verifyPrimaryImage },
    .{ .file = corpus_dir ++ "/image_extension.fits", .gen = genImageExtension, .verify = verifyImageExtension },
    .{ .file = corpus_dir ++ "/ascii_table.fits", .gen = genAsciiTable, .verify = verifyAsciiTable },
    .{ .file = corpus_dir ++ "/binary_table.fits", .gen = genBinaryTable, .verify = verifyBinaryTable },
    .{ .file = corpus_dir ++ "/binary_table_vla.fits", .gen = genBinaryTableVla, .verify = verifyBinaryTableVla },
    .{ .file = corpus_dir ++ "/compressed_image.fits.gz", .gen = genCompressedImage, .verify = verifyCompressedImage },
};

test "corpus: committed on-disk files round-trip via openFile (NFR-TEST-2)" {
    const alloc = std.testing.allocator;

    // A blocking I/O context for the directory/existence probes (the same single-threaded
    // backend `FileDevice` uses internally). All file *contents* still flow through the public
    // `openFile`/`createFile` API, which manages its own I/O.
    var threaded: std.Io.Threaded = .init_single_threaded;
    const io = threaded.io();
    const cwd = std.Io.Dir.cwd();

    // Ensure the corpus directory exists (a no-op when the committed files are present;
    // mkdir -p semantics tolerate the existing directory).
    cwd.createDirPath(io, corpus_dir) catch {};

    for (members) |m| {
        // Read the committed file directly; (re)generate only when it is missing so a fresh
        // checkout/clone is self-healing while CI exercises the committed bytes.
        const present = if (cwd.access(io, m.file, .{})) |_| true else |_| false;
        if (!present) try m.gen(alloc, m.file);
        try m.verify(alloc, m.file);
    }
}
